name: incident_manager
description: A Flutter package for managing incidents in event management applications.
version: 1.0.0
homepage: https://github.com/your-username/incident_manager

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  blink_component:
#    path: ../blink_component
    git:
       url: git@github.com:blink-global/blink_component.git
       ref: incident-module-changes

  get: ^4.6.6
  dio: ^5.4.1
  retrofit: ^4.1.0
#  json_annotation: ^4.8.1
  equatable: ^2.0.5
  intl: ^0.20.2
  fl_chart: ^1.0.0
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  dio_http_cache_lts: ^0.4.2
  conditional_builder_null_safety: ^0.0.6
  readmore: ^2.2.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.2.5
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  retrofit_generator: ^10.0.0

flutter:
  # Add any assets, fonts, etc. here if needed
